name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: jekyll/jekyll:3.8.5
    steps:
    - run: whoami
    - uses: actions/checkout@v2
    - run: ls -lah $GITHUB_WORKSPACE
    - name: Update the gemfiles
      run: whoami && bundle update
      working-directory: jekyll
