name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: jekyll/jekyll:3.8.5
    steps:
    - uses: actions/checkout@v2
     
    - name: Copy checked out files to Jekyll working directory
      run: cp -r $GITHUB_WORKSPACE/jekyll/ /srv/jekyll/
     
    - run: ls /srv/jekyll
      
    - name: Update the gemfiles
      run: bundle update
