name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: jekyll/builder:3.8.5
    steps:    
    - name: Checkout the code into GITHUB_WORKSPACE
      uses: actions/checkout@v2
      
    - name: Change the directory to be owned by the user inside the docker container
      run: chmod -R a+w $GITHUB_WORKSPACE
  
    - name: Update the gemfiles
      run: bundle update && jekyll build
      working-directory: jekyll
