name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    #container: 
    #  image: jekyll/jekyll:3.8.5
    steps:
    - uses: actions/checkout@2v
      
    - name: Update the gemfiles
      run: bundle update
